### ISSUE TITLE
fails to parse typical .env file format

### ISSUE THREAD

**Issue by kennethkoontz** [crystalschang/gulp-env#5] opened 2015-01-29 03:29 UTC
``` bash
➜  benchmark-client git:(51_split_sites) ✗ gulp load-envs
[19:22:17] Using gulpfile ~/Projects/benchmark-client/gulpfile.js
[19:22:17] Starting 'load-envs'...

/Users/kenneth/Projects/benchmark-client/.env:1
ts, require, module, __filename, __dirname) { BENCHMARK_API_URL=http://localho
                                                                    ^
[19:22:17] 'load-envs' errored after 969 μs
[19:22:17] SyntaxError: Unexpected token :
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/Users/kenneth/Projects/benchmark-client/node_modules/gulp-env/index.js:5:15)
    at Gulp.gulp.task.gulp.src.pipe.plugins.angularTemplatecache.root (/Users/kenneth/Projects/benchmark-client/gulpfile.js:28:5)
    at module.exports (/Users/kenneth/Projects/benchmark-client/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/kenneth/Projects/benchmark-client/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
```

My `.env` file is setup like:

``` bash
➜  benchmark-client git:(51_split_sites) ✗ cat .env
BENCHMARK_API_URL=http://localhost:8000
```

Thoughts on supporting this?

**Comment by russmatney** [comment] 2015-03-15 04:26
Sorry - just seeing this now. This was intended to support that style config as well (I believe that's `ini`?) 

Would happily accept a related PR, not sure when we could get to this.

**Comment by impinball** [comment] 2015-06-14 09:18
@russmatney [What do you think about my PR?](https://github.com/moveline/gulp-env/pull/6) I know it covers a little more than this, but I was also thinking about future-proofing it a little (and also making it easier to support more file types down the road).

**Comment by impinball** [comment] 2015-07-25 20:53
@crystalschang Please close this.

**Closed** 2017-02-08 19:13 UTC
